# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\include']
Supported SIMD extensions in this Num

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
X = np.zeros(10)
print(X)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
X = np.zeros((10,10))
print("%d bytes" % (X.size * X.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [6]:
'''%run `python -c "import numpy; numpy.info(numpy.add)"`  '''

'%run `python -c "import numpy; numpy.info(numpy.add)"`  '

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [7]:
X = np.zeros(10)
X[4] = 1
print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [8]:
X = np.arange(10,50)
print(X)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [9]:
X = np.arange(50)
X = X[::-1]
print(X)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [10]:
X = np.arange(9).reshape(3, 3)
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [11]:
XX = np.nonzero([1,2,0,0,4,0])
print(XX)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [12]:
X = np.eye(3)
print(X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [13]:
X = np.random.random((3,3,3))
print(X)

[[[0.04868013 0.75240599 0.90820327]
  [0.66693788 0.86281979 0.27865315]
  [0.61297584 0.14886777 0.76081673]]

 [[0.60622319 0.9645     0.30654619]
  [0.76217549 0.0633521  0.91012952]
  [0.74097344 0.71223201 0.06851794]]

 [[0.60084394 0.51825732 0.09724656]
  [0.21521316 0.18001055 0.2884336 ]
  [0.31639106 0.48295698 0.73142276]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [14]:
X = np.random.random((10,10))
Xmin, Xmax = X.min(), X.max()
print(Xmin, Xmax)

0.002672910293533781 0.9890843264946525


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [15]:
X = np.random.random(30)
B = X.mean()
print(B)

0.5114097607769676


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [16]:
X = np.ones((10,10))
X[1:-1,1:-1] = 0
print(X)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [19]:
X = np.ones((5,5))
X = np.pad(X, pad_width=1, mode='constant', constant_values=0)
print(X)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [20]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [21]:
X = np.diag(1+np.arange(4),k=-1)
print(X)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [22]:
X = np.zeros((8,8),dtype=int)
X[1::2,::2] = 1
X[::2,1::2] = 1
print(X)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [23]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [24]:
X = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(X)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [25]:
X = np.random.random((5,5))
X = (X - np.mean (X)) / (np.std (X))
print(X)

[[-1.62233353 -0.42615419  1.15910002  0.95942453  1.62279229]
 [ 1.15604856 -1.3591529   1.083084   -0.91126069  0.1982222 ]
 [-1.00868057 -1.60210383  0.39461039  0.24375395  1.24951202]
 [ 1.05081957  0.26891081  0.53234238  0.74268908 -1.51965654]
 [-1.10627412  0.32172674 -0.92177409 -0.44795055 -0.05769554]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [28]:
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [29]:
X = np.dot(np.ones((5,3)), np.ones((3,2)))
print(X)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [30]:
X = np.arange(11)
X[(3 < X) & (X < 8)] *= -1
print(X)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [34]:
"""All are legal 
X**X
2 << X >> 2
X <- X
1j*X
X/1/1
X<X>X"""

'All are legal \nX**X\n2 << X >> 2\nX <- X\n1j*X\nX/1/1\nX<X>X'

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [35]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\LENOVO\AppData\Local\Temp\ipykernel_6696\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_6696\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [36]:
X = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(X)), X))

[-3. -9. -8.  1. -3. -2.  3. -3.  2.  9.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [37]:
X1 = np.random.randint(0,10,10)
X2 = np.random.randint(0,10,10)
print(np.intersect1d(X1,X2))

[1 3 4]


31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [38]:
"""# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0 """

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [40]:
"""False"""

'False'

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [42]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [43]:
X = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(X)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [44]:
D = np.ones(3)*1
C = np.ones(3)*2
np.add(D,C,out=C)
np.divide(D,2,out=D)
np.negative(D,out=D)
np.multiply(D,C,out=D)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [45]:
X = np.random.uniform(0,10,10)

print(X - X%1)
print(X // 1)
print(np.floor(X))
print(X.astype(int))
print(np.trunc(X))

[3. 6. 2. 9. 1. 3. 9. 9. 9. 9.]
[3. 6. 2. 9. 1. 3. 9. 9. 9. 9.]
[3. 6. 2. 9. 1. 3. 9. 9. 9. 9.]
[3 6 2 9 1 3 9 9 9 9]
[3. 6. 2. 9. 1. 3. 9. 9. 9. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [46]:
X = np.zeros((5,5))
X += np.arange(5)
print(X)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [47]:
def generate():
    for x in range(10):
        yield x
X = np.fromiter(generate(),dtype=float,count=-1)
print(X)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [48]:
X = np.linspace(0,1,11,endpoint=False)[1:]
print(X)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [49]:
X = np.random.random(10)
X.sort()
print(X)

[0.14341813 0.4293105  0.50446239 0.5099722  0.60205554 0.60269202
 0.63147598 0.65351447 0.68250088 0.84731882]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [50]:
X = np.arange(10)
np.add.reduce(X)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [52]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [54]:
"""
X = np.zeros(10)
X.flags.writeable = False
X[0] = 1
"""

'\nX = np.zeros(10)\nX.flags.writeable = False\nX[0] = 1\n'

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [55]:
X = np.random.random((10,2))
Q,R = X[:,0], X[:,1]
U = np.sqrt(Q**2+R**2)
T = np.arctan2(R,Q)
print(U)
print(T)

[0.30693606 0.67928899 0.86214478 0.17189985 0.95484865 0.82056466
 1.13402477 0.29888464 0.71953941 0.91449131]
[0.12640749 0.24273661 1.54102412 0.95572436 1.47587923 1.45603686
 0.93383036 0.31491332 1.11683364 1.24364676]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [56]:
X = np.random.random(10)
X[X.argmax()] = 0
print(X)

[0.60902527 0.5972491  0.10377069 0.85238804 0.82013027 0.28232523
 0.87783784 0.         0.65857113 0.73349612]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [58]:
X = np.zeros((5,5), [('x',float),('y',float)])
X['x'], X['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(X)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [60]:
Q = np.arange(8)
R = Q + 0.5
C = 1.0 / np.subtract.outer(Q, R)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [61]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [62]:
np.set_printoptions(threshold=float("inf"))
X = np.zeros((40,40))
print(X)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [63]:
X = np.arange(100)
G = np.random.uniform(0,100)
index = (np.abs(X-G)).argmin()
print(X[index])

14


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [64]:
X = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(X)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\LENOVO\AppData\Local\Temp\ipykernel_6696\3108791801.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  X = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [65]:
X = np.random.random((10,2))
Q,R = np.atleast_2d(X[:,0], X[:,1])
E = np.sqrt( (Q-Q.T)**2 + (R-R.T)**2)
print(E)

[[0.         0.6291266  0.51010185 0.08648019 0.68705979 0.50067264
  0.94549312 0.28575156 0.13769663 0.34435853]
 [0.6291266  0.         0.81619202 0.68901325 0.58631363 0.17901974
  0.36803438 0.56852759 0.71563653 0.76057305]
 [0.51010185 0.81619202 0.         0.44747958 0.42615384 0.79469025
  0.96725433 0.28377777 0.40216384 0.1748018 ]
 [0.08648019 0.68901325 0.44747958 0.         0.67495914 0.57274524
  0.98782287 0.26341365 0.05285197 0.27541535]
 [0.68705979 0.58631363 0.42615384 0.67495914 0.         0.66086617
  0.59307598 0.41171604 0.65651887 0.51076685]
 [0.50067264 0.17901974 0.79469025 0.57274524 0.66086617 0.
  0.54705239 0.51931301 0.60860058 0.70306306]
 [0.94549312 0.36803438 0.96725433 0.98782287 0.59307598 0.54705239
  0.         0.79535477 1.00139423 0.97475204]
 [0.28575156 0.56852759 0.28377777 0.26341365 0.41171604 0.51931301
  0.79535477 0.         0.24655503 0.19210056]
 [0.13769663 0.71563653 0.40216384 0.05285197 0.65651887 0.60860058
  1.00139423 0.24655

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [66]:
X = (np.random.rand(10)*100).astype(np.float32)
R = X.view(np.int32)
R[:] = X
print(R)

[ 5 15 13 25 39 35 11 45 73 20]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [68]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
X = np.genfromtxt(s, delimiter=",", dtype=np.int64)
print(X)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [70]:
X = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(X):
    print(index, value)
for index in np.ndindex(X.shape):
    print(index, X[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [71]:
Q, R = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
E = np.sqrt(Q*Q+R*R)
sigma, mu = 1.0, 0.0
H = np.exp(-( (E-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(H)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [72]:
n = 10
p = 3
X = np.zeros((n,n))
np.put(X, np.random.choice(range(n*n), p, replace=False),1)
print(X)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [78]:
Q = np.random.rand(5, 10)

R = Q - Q.mean(axis=1, keepdims=True)

print(R)

[[-0.3603746   0.25560818 -0.59249502  0.27024361  0.1337398   0.17717084
   0.37479145 -0.05484404 -0.50617412  0.30233389]
 [ 0.43392934 -0.33789996 -0.17915825 -0.08063267 -0.26543378  0.32656018
  -0.39347882 -0.0068162   0.36104156  0.1418886 ]
 [ 0.12690923 -0.40225277  0.02105195 -0.37752198  0.22416961  0.30106078
   0.04347463 -0.2873724   0.227282    0.12319895]
 [ 0.01711938 -0.2527244   0.36620169 -0.26701376 -0.05116231 -0.53913607
  -0.20433948  0.35552624  0.2091642   0.36636451]
 [-0.48309286 -0.49392685 -0.18030534  0.14851634  0.41583394  0.31462504
  -0.45093011  0.20129001  0.30380427  0.22418555]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [79]:
X = np.random.randint(0,10,(3,3))
print(X)
print(X[X[:,1].argsort()])

[[9 2 1]
 [5 5 5]
 [3 0 7]]
[[3 0 7]
 [9 2 1]
 [5 5 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [80]:
X = np.random.randint(0,3,(3,10))
print((~X.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [83]:
X = np.random.uniform(0,1,10)
x = 0.5
m = X.flat[np.abs(X - x).argmin()]
print(m)

0.5184446738088473


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [84]:
D = np.arange(3).reshape(3,1)
C = np.arange(3).reshape(1,3)
it = np.nditer([D,C,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [85]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

X = NamedArray(np.arange(10), "range_10")
print (X.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [86]:
X = np.ones(10)
I = np.random.randint(0,len(X),20)
X += np.bincount(I, minlength=len(X))
print(X)

[2. 3. 3. 4. 2. 3. 3. 5. 2. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [87]:
Q = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,Q)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [88]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [89]:
D = np.random.randint(0,10,(3,4,3,4))

sum = D.sum(axis=(-2,-1))
print(sum)

sum = D.reshape(D.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[82 65 48 49]
 [70 59 65 48]
 [53 45 50 59]]
[[82 65 48 49]
 [70 59 65 48]
 [53 45 50 59]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [90]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.68542252 0.52481176 0.58708797 0.48989187 0.40656973 0.40949182
 0.47426063 0.32350755 0.43288653 0.42152786]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [91]:
D = np.random.uniform(0,1,(5,5))
C = np.random.uniform(0,1,(5,5))

np.diag(np.dot(D, C))

array([2.15742315, 0.90584699, 0.92243131, 1.05064804, 2.30235062])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [93]:
X = np.array([1,2,3,4,5])
nz = 3
X0 = np.zeros(len(X) + (len(X)-1)*(nz))
X0[::nz+1] = X
print(X0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [94]:
D = np.ones((5,5,3))
C = 2*np.ones((5,5))
print(D * C[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [95]:
D = np.arange(25).reshape(5,5)
D[[0,1]] = D[[1,0]]
print(D)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [96]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
H = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
H = np.unique(H)
print(H)

[( 4, 37) ( 4, 82) ( 6, 72) ( 6, 93) ( 7, 71) ( 7, 83) (10, 31) (10, 40)
 (18, 25) (18, 83) (20, 54) (20, 64) (25, 83) (27, 44) (27, 45) (30, 45)
 (30, 81) (30, 86) (30, 97) (31, 40) (37, 82) (38, 42) (38, 73) (42, 73)
 (44, 45) (45, 86) (54, 64) (71, 83) (72, 93) (81, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [97]:
c = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(c)), c)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [98]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
X = np.arange(20)
print(moving_average(X, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [99]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
X = rolling(np.arange(10), 3)
print(X)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [100]:
X = np.random.randint(0,2,100)
np.logical_not(X, out=X)

X = np.random.uniform(-1.0,1.0,100)
np.negative(X, out=X)

array([-0.07394995,  0.22371903, -0.4455876 ,  0.23597928, -0.58118042,
        0.16369033,  0.44812202,  0.95361149,  0.51739038, -0.72433081,
       -0.70621262,  0.33710322, -0.72409452,  0.3155299 , -0.41598654,
       -0.92280731,  0.09101961,  0.40543111,  0.27776948, -0.56086287,
       -0.72722797, -0.60707028, -0.26645609,  0.55448588, -0.89062175,
       -0.49719897, -0.96931977, -0.10962223, -0.34066489,  0.86888638,
       -0.93834839,  0.82711331,  0.73826557, -0.55233436, -0.75522409,
       -0.0990826 , -0.70014745, -0.42899553, -0.19298211,  0.70904077,
        0.04662518, -0.91851513,  0.55670022, -0.55209107,  0.34068185,
       -0.02224497, -0.14554157,  0.5906013 ,  0.80772249, -0.71537279,
       -0.18732946,  0.31642035,  0.18041917, -0.60846246,  0.22748142,
       -0.89588138, -0.75907142,  0.28557856,  0.23393259, -0.85907763,
        0.34680898, -0.06595456,  0.35503842,  0.74173302, -0.24026286,
        0.55226894,  0.29656978,  0.87928825,  0.88158521,  0.64

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [101]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.94228132 10.8561238  13.95395989  2.93950436  3.09717078 15.56286873
  7.64722339  0.78772681  2.23250951  5.1331864 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [102]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.28970784  6.40540309 11.9806157   2.71767975 12.28621716 14.47787745
   8.7948798   2.5419446   1.53974357  8.13292985]
 [ 6.11643028  5.23874743  1.51059675  1.08545322  1.89969377  6.28615888
   0.98440692  0.16852741 10.11595893  1.24237649]
 [ 8.06671166  3.83967327  3.91314868  1.66258796  4.3257054   9.04328646
   0.22238319  1.86160777  8.60462104  1.448529  ]
 [ 0.26124161 10.49849774  6.78354217  9.93902859  6.4610414   2.93577867
   2.75254166  6.30754944 15.726254    1.3267794 ]
 [ 9.78152111  5.46000699  3.11669498  2.45549727  3.56019788  8.9264564
   1.84578029  3.52798868 10.16257849  3.52216672]
 [ 9.07346967  3.90542499  4.72099548 15.52376541  4.55888966  4.28537891
  12.91826482 15.47134111  9.50112221  8.48255441]
 [ 0.20026915  3.04182934  6.80371405  2.68961518  7.07044812  8.7774518
   9.73669294  6.21061082  2.0356845   7.93092089]
 [ 8.25128186  0.3500539   0.03267661 12.27768172  0.19140251  0.14471483
  14.39499943 14.46291922  5.15159239 10.82920032]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [103]:
X = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

U = np.ones(shape, dtype=X.dtype)*fill
P  = np.array(list(position)).astype(int)
Us = np.array(list(U.shape)).astype(int)
Xs = np.array(list(X.shape)).astype(int)

U_start = np.zeros((len(shape),)).astype(int)
U_stop  = np.array(list(shape)).astype(int)
X_start = (P-Us//2)
X_stop  = (P+Us//2)+Us%2

U_start = (U_start - np.minimum(X_start,0)).tolist()
X_start = (np.maximum(X_start,0)).tolist()
U_stop = np.maximum(U_start, (U_stop - np.maximum(X_stop-Xs,0))).tolist()
X_stop = (np.minimum(X_stop,Xs)).tolist()

u = [slice(start,stop) for start,stop in zip(U_start,U_stop)]
x = [slice(start,stop) for start,stop in zip(X_start,X_stop)]
U[u] = X[x]
print(X)
print(U)

[[6 3 8 8 8 6 7 9 2 5]
 [9 8 0 1 7 8 0 5 1 7]
 [0 9 5 2 6 7 3 6 0 7]
 [7 9 0 5 2 0 0 4 6 4]
 [8 9 9 1 4 2 6 2 5 1]
 [2 0 0 2 5 5 2 1 1 5]
 [6 4 7 6 0 4 9 0 9 2]
 [7 4 9 7 6 1 0 4 0 9]
 [0 9 8 6 2 3 5 9 4 8]
 [5 4 6 7 7 3 6 0 6 8]]
[[0 0 0 0 0]
 [0 6 3 8 8]
 [0 9 8 0 1]
 [0 0 9 5 2]
 [0 7 9 0 5]]


C:\Users\LENOVO\AppData\Local\Temp\ipykernel_6696\2955616044.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  U[u] = X[x]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [14]:
import numpy as np
Z = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [8]:
X = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(X) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)


10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [9]:
X = np.random.randint(0,10,50)
print(np.bincount(X).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [15]:
X = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (X.shape[0]-3)
j = 1 + (X.shape[1]-3)
C = np.lib.stride_tricks.as_strided(X, shape=(i, j, n, n), strides=X.strides + X.strides)
print(C)

[[[[4 1 2]
   [1 3 1]
   [4 1 4]]

  [[1 2 2]
   [3 1 3]
   [1 4 2]]

  [[2 2 1]
   [1 3 4]
   [4 2 4]]

  [[2 1 1]
   [3 4 3]
   [2 4 0]]

  [[1 1 3]
   [4 3 4]
   [4 0 1]]

  [[1 3 0]
   [3 4 1]
   [0 1 0]]

  [[3 0 0]
   [4 1 4]
   [1 0 0]]

  [[0 0 1]
   [1 4 3]
   [0 0 0]]]


 [[[1 3 1]
   [4 1 4]
   [3 3 1]]

  [[3 1 3]
   [1 4 2]
   [3 1 3]]

  [[1 3 4]
   [4 2 4]
   [1 3 0]]

  [[3 4 3]
   [2 4 0]
   [3 0 2]]

  [[4 3 4]
   [4 0 1]
   [0 2 2]]

  [[3 4 1]
   [0 1 0]
   [2 2 1]]

  [[4 1 4]
   [1 0 0]
   [2 1 3]]

  [[1 4 3]
   [0 0 0]
   [1 3 3]]]


 [[[4 1 4]
   [3 3 1]
   [4 4 2]]

  [[1 4 2]
   [3 1 3]
   [4 2 1]]

  [[4 2 4]
   [1 3 0]
   [2 1 3]]

  [[2 4 0]
   [3 0 2]
   [1 3 1]]

  [[4 0 1]
   [0 2 2]
   [3 1 4]]

  [[0 1 0]
   [2 2 1]
   [1 4 4]]

  [[1 0 0]
   [2 1 3]
   [4 4 0]]

  [[0 0 0]
   [1 3 3]
   [4 0 4]]]


 [[[3 3 1]
   [4 4 2]
   [0 1 3]]

  [[3 1 3]
   [4 2 1]
   [1 3 4]]

  [[1 3 0]
   [2 1 3]
   [3 4 1]]

  [[3 0 2]
   [1 3 1]
   [4 1 1]]

  [[0 2 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [16]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9 13  8 11  9]
 [13  0  6 15  7]
 [ 8  6  9 42 17]
 [11 15 42  2 12]
 [ 9  7 17 12  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [17]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [18]:
X = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(X, np.arange(0, X.shape[0], k), axis=0),
                                       np.arange(0, X.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [27]:
def iterate(Z):
    
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [29]:
X = np.arange(10000)
np.random.shuffle(X)
n = 5

print (X[np.argsort(X)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [30]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [31]:
X = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
U = np.core.records.fromarrays(X.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(U)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [32]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.69 s ± 29 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
468 ms ± 25.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
295 ms ± 9.92 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [33]:
D = np.random.randint(0,5,(8,3))
C = np.random.randint(0,5,(2,2))

A = (D[..., np.newaxis, np.newaxis] == C)
rows = np.where(A.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [34]:
X = np.random.randint(0,5,(10,3))
print(X)

E = np.all(X[:,1:] == X[:,:-1], axis=1)
U = X[~E]
print(U)

U = X[X.max(axis=1) != X.min(axis=1),:]
print(U)

[[1 2 2]
 [3 2 0]
 [3 0 4]
 [2 1 2]
 [3 3 0]
 [2 1 3]
 [4 3 0]
 [4 2 0]
 [3 2 3]
 [0 1 2]]
[[1 2 2]
 [3 2 0]
 [3 0 4]
 [2 1 2]
 [3 3 0]
 [2 1 3]
 [4 3 0]
 [4 2 0]
 [3 2 3]
 [0 1 2]]
[[1 2 2]
 [3 2 0]
 [3 0 4]
 [2 1 2]
 [3 3 0]
 [2 1 3]
 [4 3 0]
 [4 2 0]
 [3 2 3]
 [0 1 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [35]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [36]:
X = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(X).view(np.dtype((np.void, X.dtype.itemsize * X.shape[1])))
_, idx = np.unique(T, return_index=True)
uX = X[idx]
print(uX)

[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [37]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)  

array([[6.51373697e-02, 2.94399282e-02, 2.34517012e-01, 6.27922668e-04,
        4.10944831e-01, 4.89299381e-01, 3.86528259e-01, 3.68325528e-01,
        2.01114314e-02, 5.04330686e-01],
       [2.13993398e-02, 9.67179104e-03, 7.70450090e-02, 2.06289118e-04,
        1.35006190e-01, 1.60747721e-01, 1.26984703e-01, 1.21004627e-01,
        6.60713438e-03, 1.65685900e-01],
       [9.86794096e-02, 4.45998165e-02, 3.55279932e-01, 9.51267120e-04,
        6.22558040e-01, 7.41260726e-01, 5.85568323e-01, 5.57992222e-01,
        3.04676745e-02, 7.64032298e-01],
       [6.74143198e-02, 3.04690341e-02, 2.42714818e-01, 6.49872411e-04,
        4.25309870e-01, 5.06403391e-01, 4.00039789e-01, 3.81200761e-01,
        2.08144491e-02, 5.21960132e-01],
       [8.32892867e-02, 3.76439920e-02, 2.99870178e-01, 8.02906708e-04,
        5.25463370e-01, 6.25653086e-01, 4.94242600e-01, 4.70967290e-01,
        2.57159106e-02, 6.44873185e-01],
       [4.25215758e-02, 1.92183403e-02, 1.53092349e-01, 4.09906961e-04,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [38]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [39]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [40]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.23855661  0.15321293]
